name: gym_app
description: Gym App with bloc stateManagment, service locator and firebase

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg:
#  shared_preferences: ^2.0.18
  shimmer: ^3.0.0
  provider: ^6.0.5
  jiffy: ^6.4.3
  logger: ^2.6.1
  firebase_core: ^4.0.0
  firebase_auth:
  lottie: ^3.3.1 #Animations
  internet_connection_checker:
#  open_mail_app: ^0.4.5
  url_launcher:
  persistent_bottom_nav_bar: ^6.2.1
#  qr_code_scanner: ^1.0.1
  cloud_firestore: ^6.0.0
  mobile_scanner:
  table_calendar_jalali:
  google_fonts: ^6.3.0
  get_it: ^8.2.0
  firebase_storage: ^13.0.0
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.2.3
  google_sign_in: ^7.1.1
  equatable: ^2.0.5
  circular_countdown_timer: ^0.2.3
  image_picker: ^1.2.0
  path: ^1.8.0
  intl: ^0.20.2
  flutter_rating_bar: ^4.0.1
  easy_localization: ^3.0.0-nullsafety  # Use a version compatible with shared_preferences
  shared_preferences: ^2.0.18
  onesignal_flutter: ^5.3.4
  awesome_notifications: ^0.10.1
  rename: ^3.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.jpeg"

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/animations/disconnected_network.json
    - assets/icons/bottomNavIcons/
    - assets/icons/bottomNavIcons/bottomNavSelected/
    - assets/icons/bottomNavIcons/bottomNavUnSelected/
    - assets/translations/

  fonts:
    - family: Avenir Arabic
      fonts:
        - asset: assets/fonts/Avenir Black.ttf
          weight: 700
        - asset: assets/fonts/Avenir Regular.ttf
          weight: 400

    - family: Bebas
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
          weight: 400

